PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT ?versionIRI ?IRI ?title

WHERE {
  ?IRI a owl:Ontology .
  OPTIONAL { ?IRI owl:versionIRI ?versionIRI . }
  OPTIONAL { ?IRI dc:title ?title . }
}
